# Generated by Django 4.2.16 on 2025-01-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDoctorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('department', models.CharField(default='department', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Hospital_media')),
            ],
        ),
        migrations.CreateModel(
            name='AdminPatientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=5, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=10, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('coverage_details', models.TextField(null=True)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_deductible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('insurance_number', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('billing_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.billingdetail')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.insurance')),
            ],
        ),
    ]
