# Generated by Django 4.2.16 on 2025-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
