# Generated by Django 4.2.16 on 2025-01-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_contacttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttable',
            name='message',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
