# Generated by Django 4.2.16 on 2025-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_billingdetail_country_billingdetail_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
