# Generated by Django 4.2.16 on 2025-01-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_contacttable_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintable',
            name='images',
        ),
    ]
