# Generated by Django 4.2.16 on 2025-01-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_billingdetail_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
    ]
