# Generated by Django 4.2.16 on 2025-01-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_remove_logintable_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpatienttable',
            name='imge',
        ),
    ]
